Handle wrong extension in optimize_image()
openzim/python_scraperlib pull request #65
Opened 2020-09-16 09:10 UTC by satyamtg

This fixes #64 by handling wrong extension while optimizing images. It creates a copy of the original file with correct extension if wrong extension is found. 

Also, unrelated - Use correct directory in the yt_downloader context manager test to not have files downloaded in workdir,

2020-09-18 13:44 UTC, rgaudin requested changes
I think it's a wrong way to handle this.
The root cause of this is that we use actual-data based detection in `optimize_image` while we use extension-based one in dedicated functions (via `ensure_matches`).
We can handle this by just adding `from_suffix=False` in `ensure_matches()`. That's it.

We should be very careful about creating stuff on the filesystem in the scraperlib, especially for stuff as common as image optimization as this is the kind of barely noticeable resource usage in tests that become a huge bottleneck when scaled-up.

You'll notice that `test_optimize_webp_gif_failure()` then fails because it's actually not testing what it should: it is ensuring a manually created file is being properly deleted upon optimization failure. That's not correct.

2020-09-18 14:49 UTC, satyamtg commented
Okay. I understand. I initially thought of doing it this way because I thought about the fact that if we use some external tool, it might throw errors for wrong extension (which seems to happen quite frequently in case of some scrapers). 
But I get the point now about the filesystem usage. I have also checked gifsicle for these kinds of errors, but it seems its not the case with it. I'm rebasing and doing `from_suffix=True` in the individual optimizers. If in future we add another external tool, we shall check for extension errors and if they occur, we shall handle that in the individual function itself.

2020-09-18 14:54 UTC, rgaudin commented
Yes, AFAIK, only gif uses an external tool so we should have a dedicated test for that as well.
For GIF, because of this specific requirement, we could test both format and extension but I don't think we should handle that in the lib. The scraper should rename source if it's incorrect I think.

2020-09-18 15:05 UTC, satyamtg commented
> Yes, AFAIK, only gif uses an external tool so we should have a dedicated test for that as well.

Rebased it. I read this later though. I haven't added a test yet because gifsicle doesn't have problems with wrong extensions. I think we can add that if there's some external module that gives problems (maybe in the future). What do you think?

2020-09-18 16:09 UTC, rgaudin submitted a review, later dismissed

2020-09-18 16:18 UTC, satyamtg commented
> Yes, AFAIK, only gif uses an external tool so we should have a dedicated test for that as well.
> For GIF, because of this specific requirement, we could test both format and extension but I don't think we should handle that in the lib. The scraper should rename source if it's incorrect I think.

I also added a fallback to suffix check if Pillow was not able to identify format (allowed the last two tests to pass)

2020-09-21 09:54 UTC, rgaudin approved these changes
Nope, I don't think it's a good idea. What's the use case for this? An image for which the format can't be guessed by Pillow? Then we cannot ensure it's the right format (actually it's almost certain it's not). So this will most likely fail later.
I don't see the value of doing this.

Changing our code just to please some tests that are not testing what they should seems wrong.
I've reverted this change and updated the tests so that we enter the exception block.
Used incorrect params to do so.

2020-09-21 09:58 UTC, merged